In [87]:
import pandas as pd
import numpy as np
from glob import glob
import os

In [3]:
folder = '.'
file_names = glob(os.path.join(folder, '*/*.xlsx'))
data_raw = []
for i in range(len(file_names)):
    data_raw.append(pd.read_excel(file_names[i]))

In [47]:
#for i in range(len(file_names)):
for i in range(1):
    for col in data_raw[i].columns:
        n = data_raw[i][col].notna().sum()
        #print(cols)
        print(col, n)

측정날짜 8739
수계 8739
측정소명 8739
MSR_DATE_R 8739
총유기탄소 8044
염화메틸렌 7363
독성도(발광박테리아) 5720
1.1.1-트리클로로에테인 7347
벤젠 7347
사염화탄소 7347
트리클로로에틸렌 7347
톨루엔 7347
테트라클로로에틸렌 7347
에틸벤젠 7347
m,p-자일렌 7347
o-자일렌 7347
[ECD]염화메틸렌 7319
[ECD]1.1.1-트리클로로에테인 7343
[ECD]사염화탄소 7343
[ECD]트리클로로에틸렌 7343
[ECD]테트라클로로에틸렌 7343
클로로필-a 7557
수온 7985
수소이온농도 7985
전기전도도 7984
용존산소 7980
독성지수(좌) 7420
유영속도(좌) 7420
개체수(좌) 7420
독성지수(우) 7443
유영속도(우) 7443
개체수(우) 7443
탁도 7978

**remove 경안천**

In [84]:
file_names = file_names[1:]
file_names

['./자동측정망_팔당상수원보호구역_시간자료2018/서상2018.xlsx',
 './자동측정망_팔당상수원보호구역_시간자료2018/화천2018.xlsx',
 './자동측정망_팔당상수원보호구역_시간자료2018/가평2018.xlsx',
 './자동측정망_팔당상수원보호구역_시간자료2018/양평2018.xlsx']

In [48]:
df_index = data_raw[1].columns
for i in range(2, len(file_names)):
    df_index = df_index.intersection(data_raw[i].columns)

In [49]:
df_index

Index(['측정날짜', '수계', '측정소명', 'MSR_DATE_R', '총유기탄소', '총질소', '총인', '수온',
       '수소이온농도', '전기전도도', '용존산소', '탁도'],
      dtype='object')

In [55]:
cols = df_index[[4,5,6,7]]

In [78]:
'''
df_list = []
for i in range(1, len(file_names)):
    df_list.append(data_raw[i][cols])

df_all = pd.concat(df_list, axis=0)
df_all
'''

'\ndf_list = []\nfor i in range(1, len(file_names)):\n    df_list.append(data_raw[i][cols])\n\ndf_all = pd.concat(df_list, axis=0)\ndf_all\n'

In [81]:
df_filtered = []
for i in range(0, len(file_names)):
    df_filtered.append(data_raw[i][cols])

In [89]:
print('total time seris =', len(is_nan), 'nan count =', is_nan.sum())

total time seris = 43698 nan count = 14712

In [5]:
df.columns

Index(['측정날짜', '수계', '측정소명', 'MSR_DATE_R', '총유기탄소', '염화메틸렌', '독성도(발광박테리아)',
       '1.1.1-트리클로로에테인', '벤젠', '사염화탄소', '트리클로로에틸렌', '톨루엔', '테트라클로로에틸렌', '에틸벤젠',
       'm,p-자일렌', 'o-자일렌', '[ECD]염화메틸렌', '[ECD]1.1.1-트리클로로에테인', '[ECD]사염화탄소',
       '[ECD]트리클로로에틸렌', '[ECD]테트라클로로에틸렌', '클로로필-a', '수온', '수소이온농도', '전기전도도',
       '용존산소', '독성지수(좌)', '유영속도(좌)', '개체수(좌)', '독성지수(우)', '유영속도(우)', '개체수(우)',
       '탁도'],
      dtype='object')

In [6]:
df

,측정날짜,수계,측정소명,MSR_DATE_R,총유기탄소,염화메틸렌,독성도(발광박테리아),1.1.1-트리클로로에테인,벤젠,사염화탄소,...,수소이온농도,전기전도도,용존산소,독성지수(좌),유영속도(좌),개체수(좌),독성지수(우),유영속도(우),개체수(우),탁도
0,20180101000000,한강,경안천,20180101000000,2.38667,0.0,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,1.0,0.55750,14.00000,0.0,0.58917,15.00000,NaN
1,20180101010000,한강,경안천,20180101010000,2.40667,0.0,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.53583,14.00000,0.0,0.59083,15.00000,NaN
2,20180101020000,한강,경안천,20180101020000,2.38000,0.0,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.55917,14.00000,0.0,0.57167,15.00000,NaN
3,20180101030000,한강,경안천,20180101030000,2.38333,0.0,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.57083,14.00000,0.0,0.58583,15.00000,NaN
4,20180101040000,한강,경안천,20180101040000,2.42167,0.0,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,0.0,0.58000,14.00000,0.0,0.57167,15.00000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8734,20181231190000,한강,경안천,20181231190000,2.33000,0.0,-5.90000,0.0,0.0,0.0,...,7.5,439.50000,14.05000,0.0,0.39917,9.75000,0.0,0.42833,13.50000,NaN
8735,20181231200000,한강,경안천,20181231200000,2.38250,0.0,-7.61667,0.0,0.0,0.0,...,7.5,440.00000,14.15833,0.0,0.40583,10.08333,0.0,0.41250,13.33333,0.9
8736,20181231210000,한강,경안천,20181231210000,2.42667,0.0,-5.28833,0.0,0.0,0.0,...,7.5,440.66667,14.30000,0.0,0.39333,9.66667,0.0,0.40833,13.16667,0.9
8737,20181231220000,한강,경안천,20181231220000,2.44333,0.0,-2.19667,0.0,0.0,0.0,...,7.5,441.25000,14.33333,0.0,0.39333,10.25000,0.0,0.42167,12.50000,NaN
8738,20181231230000,한강,경안천,20181231230000,2.51500,0.0,-6.40833,0.0,0.0,0.0,...,7.5,442.75000,14.40000,0.0,0.38167,9.83333,0.0,0.41167,12.75000,NaN